[options]
girs_dir = "gir-files"
library = "GstWebRTC"
version = "1.0"
min_cfg_version = "1.12"
target_path = "gstreamer-webrtc"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true

external_libraries = [
    "GLib",
    "GObject",
    "Gst",
]

generate = [
]

manual = [
]
